-- AlterTable
ALTER TABLE `admin` MODIFY `created_at` DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3),
    MODIFY `updated_at` DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3);

-- AlterTable
ALTER TABLE `category` MODIFY `created_at` DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3),
    MODIFY `updated_at` DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3);

-- AlterTable
ALTER TABLE `comments` MODIFY `created_at` DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3),
    MODIFY `updated_at` DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3);

-- AlterTable
ALTER TABLE `order` MODIFY `created_at` DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3);

-- AlterTable
ALTER TABLE `products` MODIFY `created_at` DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3),
    MODIFY `updated_at` DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3);

-- AlterTable
ALTER TABLE `users` MODIFY `created_at` DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3),
    MODIFY `updated_at` DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3);
