insert into Products (id, name, qte, price, admin_id, Category_id) values (1, 'Blouse / Shirt / Sweater', 705, 768.403, true, 1);
insert into Products (id, name, qte, price, admin_id, Category_id) values (2, 'Wine - Saint Emilion Calvet', 937, 332.955, false, 2);
insert into Products (id, name, qte, price, admin_id, Category_id) values (3, 'Lobster - Baby, Boiled', 67, 892.776, true, 3);
insert into Products (id, name, qte, price, admin_id, Category_id) values (4, 'Bulgar', 481, 918.268, true, 4);
insert into Products (id, name, qte, price, admin_id, Category_id) values (5, 'Tomatoes - Vine Ripe, Yellow', 953, 761.863, true, 5);
insert into Products (id, name, qte, price, admin_id, Category_id) values (6, 'Garbage Bag - Clear', 346, 64.238, true, 6);
insert into Products (id, name, qte, price, admin_id, Category_id) values (7, 'Island Oasis - Lemonade', 489, 365.437, true, 7);
insert into Products (id, name, qte, price, admin_id, Category_id) values (8, 'Lettuce - Green Leaf', 469, 554.034, false, 8);
insert into Products (id, name, qte, price, admin_id, Category_id) values (9, 'Pepper - Pablano', 342, 648.047, false, 9);
insert into Products (id, name, qte, price, admin_id, Category_id) values (10, 'Kaffir Lime Leaves', 465, 610.273, false, 10);
insert into Products (id, name, qte, price, admin_id, Category_id) values (11, 'Pastry - Baked Scones - Mini', 647, 784.947, true, 11);
insert into Products (id, name, qte, price, admin_id, Category_id) values (12, 'Basil - Fresh', 129, 25.064, true, 12);
insert into Products (id, name, qte, price, admin_id, Category_id) values (13, 'Cinnamon Rolls', 904, 841.493, true, 13);
insert into Products (id, name, qte, price, admin_id, Category_id) values (14, 'Melon - Watermelon, Seedless', 997, 734.096, true, 14);
insert into Products (id, name, qte, price, admin_id, Category_id) values (15, 'Couscous', 926, 474.754, true, 15);
insert into Products (id, name, qte, price, admin_id, Category_id) values (16, 'Gatorade - Xfactor Berry', 952, 423.319, false, 16);
insert into Products (id, name, qte, price, admin_id, Category_id) values (17, 'Appetiser - Bought', 388, 938.622, true, 17);
insert into Products (id, name, qte, price, admin_id, Category_id) values (18, 'Beef - Rib Roast, Capless', 140, 709.444, false, 18);
insert into Products (id, name, qte, price, admin_id, Category_id) values (19, 'Numi - Assorted Teas', 969, 253.555, true, 19);
insert into Products (id, name, qte, price, admin_id, Category_id) values (20, 'Oregano - Fresh', 83, 806.887, false, 20);
insert into Products (id, name, qte, price, admin_id, Category_id) values (21, 'Beef - Tenderloin Tails', 355, 839.658, false, 21);
insert into Products (id, name, qte, price, admin_id, Category_id) values (22, 'Pork - Tenderloin, Frozen', 630, 268.501, false, 22);
insert into Products (id, name, qte, price, admin_id, Category_id) values (23, 'Crab - Dungeness, Whole', 588, 233.351, false, 23);
insert into Products (id, name, qte, price, admin_id, Category_id) values (24, 'Wine - Barolo Fontanafredda', 861, 770.434, false, 24);
insert into Products (id, name, qte, price, admin_id, Category_id) values (25, 'Soup - Campbells, Butternut', 225, 515.621, true, 25);
insert into Products (id, name, qte, price, admin_id, Category_id) values (26, 'Soup - Campbells, Chix Gumbo', 620, 859.408, false, 26);
insert into Products (id, name, qte, price, admin_id, Category_id) values (27, 'Gingerale - Diet - Schweppes', 375, 429.466, true, 27);
insert into Products (id, name, qte, price, admin_id, Category_id) values (28, 'Appetizer - Mushroom Tart', 270, 611.519, false, 28);
insert into Products (id, name, qte, price, admin_id, Category_id) values (29, 'Coffee - Irish Cream', 370, 600.833, true, 29);
insert into Products (id, name, qte, price, admin_id, Category_id) values (30, 'Sardines', 795, 911.773, false, 30);
insert into Products (id, name, qte, price, admin_id, Category_id) values (31, 'Wine - Marlbourough Sauv Blanc', 437, 548.694, true, 31);
insert into Products (id, name, qte, price, admin_id, Category_id) values (32, 'Galliano', 540, 794.474, false, 32);
insert into Products (id, name, qte, price, admin_id, Category_id) values (33, 'Cheese - Brie', 685, 949.907, true, 33);
insert into Products (id, name, qte, price, admin_id, Category_id) values (34, 'Spice - Greek 1 Step', 505, 211.66, false, 34);
insert into Products (id, name, qte, price, admin_id, Category_id) values (35, 'Cookie Dough - Chocolate Chip', 505, 276.835, false, 35);
insert into Products (id, name, qte, price, admin_id, Category_id) values (36, 'Lettuce Romaine Chopped', 454, 290.652, true, 36);
insert into Products (id, name, qte, price, admin_id, Category_id) values (37, 'Grenadillo', 833, 532.719, true, 37);
insert into Products (id, name, qte, price, admin_id, Category_id) values (38, 'Beef - Roasted, Cooked', 712, 44.814, true, 38);
insert into Products (id, name, qte, price, admin_id, Category_id) values (39, 'Mushroom - King Eryingii', 423, 569.132, false, 39);
insert into Products (id, name, qte, price, admin_id, Category_id) values (40, 'Veal - Inside', 902, 812.977, true, 40);
insert into Products (id, name, qte, price, admin_id, Category_id) values (41, 'Lobak', 127, 793.7, true, 41);
insert into Products (id, name, qte, price, admin_id, Category_id) values (42, 'Wine - Lamancha Do Crianza', 162, 990.299, false, 42);
insert into Products (id, name, qte, price, admin_id, Category_id) values (43, 'Wine - Ice Wine', 248, 974.399, false, 43);
insert into Products (id, name, qte, price, admin_id, Category_id) values (44, 'Wine - Lamancha Do Crianza', 782, 932.432, true, 44);
insert into Products (id, name, qte, price, admin_id, Category_id) values (45, 'Wine - Fat Bastard Merlot', 187, 452.257, false, 45);
insert into Products (id, name, qte, price, admin_id, Category_id) values (46, 'Cake - Dulce De Leche', 172, 265.832, true, 46);
insert into Products (id, name, qte, price, admin_id, Category_id) values (47, 'Lid - 10,12,16 Oz', 564, 630.074, true, 47);
insert into Products (id, name, qte, price, admin_id, Category_id) values (48, 'Cheese - Goat', 353, 179.848, false, 48);
insert into Products (id, name, qte, price, admin_id, Category_id) values (49, 'Myers Planters Punch', 634, 4.18, false, 49);
insert into Products (id, name, qte, price, admin_id, Category_id) values (50, 'Sausage - Liver', 558, 463.283, false, 50);
