-- MySQL Script generated by MySQL Workbench
-- Wed Jun 16 14:23:16 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema craft_api
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `craft_api` ;

-- -----------------------------------------------------
-- Schema craft_api
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `craft_api` DEFAULT CHARACTER SET utf8 ;
USE `craft_api` ;

-- -----------------------------------------------------
-- Table `craft_api`.`Users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `craft_api`.`Users` ;

CREATE TABLE IF NOT EXISTS `craft_api`.`Users` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `password` TEXT NULL,
  `role` INT NULL,
  `phone` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `craft_api`.`admin`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `craft_api`.`admin` ;

CREATE TABLE IF NOT EXISTS `craft_api`.`admin` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `password` TEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `craft_api`.`Category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `craft_api`.`Category` ;

CREATE TABLE IF NOT EXISTS `craft_api`.`Category` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `state` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `craft_api`.`Products`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `craft_api`.`Products` ;

CREATE TABLE IF NOT EXISTS `craft_api`.`Products` (
  `id` INT NOT NULL,
  `name` VARCHAR(70) NULL,
  `qte` INT NULL,
  `price` DECIMAL(3) NULL,
  `Productscol` VARCHAR(45) NULL,
  `admin_id` INT NOT NULL,
  `Category_id` INT NOT NULL,
  PRIMARY KEY (`id`, `admin_id`, `Category_id`),
  INDEX `fk_Products_admin1_idx` (`admin_id` ASC) ,
  INDEX `fk_Products_Category1_idx` (`Category_id` ASC) ,
  CONSTRAINT `fk_Products_admin1`
    FOREIGN KEY (`admin_id`)
    REFERENCES `craft_api`.`admin` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Products_Category1`
    FOREIGN KEY (`Category_id`)
    REFERENCES `craft_api`.`Category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `craft_api`.`Order`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `craft_api`.`Order` ;

CREATE TABLE IF NOT EXISTS `craft_api`.`Order` (
  `id` INT NOT NULL,
  `code` INT NULL,
  `total_price` DECIMAL(3) NULL,
  `state` INT NULL,
  `Users_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Users_id`),
  INDEX `fk_Order_Users1_idx` (`Users_id` ASC) ,
  CONSTRAINT `fk_Order_Users1`
    FOREIGN KEY (`Users_id`)
    REFERENCES `craft_api`.`Users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `craft_api`.`comments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `craft_api`.`comments` ;

CREATE TABLE IF NOT EXISTS `craft_api`.`comments` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `comment` TEXT NULL,
  `Users_id` INT NOT NULL,
  `Products_id` INT NOT NULL,
  `Products_admin_id` INT NOT NULL,
  `Products_Category_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Users_id`, `Products_id`, `Products_admin_id`, `Products_Category_id`),
  INDEX `fk_comments_Users_idx` (`Users_id` ASC) ,
  INDEX `fk_comments_Products1_idx` (`Products_id` ASC, `Products_admin_id` ASC, `Products_Category_id` ASC) ,
  CONSTRAINT `fk_comments_Users`
    FOREIGN KEY (`Users_id`)
    REFERENCES `craft_api`.`Users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comments_Products1`
    FOREIGN KEY (`Products_id` , `Products_admin_id` , `Products_Category_id`)
    REFERENCES `craft_api`.`Products` (`id` , `admin_id` , `Category_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `craft_api`.`Order_has_Products`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `craft_api`.`Order_has_Products` ;

CREATE TABLE IF NOT EXISTS `craft_api`.`Order_has_Products` (
  `Order_id` INT NOT NULL,
  `Products_id` INT NOT NULL,
  `Products_admin_id` INT NOT NULL,
  `Products_Category_id` INT NOT NULL,
  PRIMARY KEY (`Order_id`, `Products_id`, `Products_admin_id`, `Products_Category_id`),
  INDEX `fk_Order_has_Products_Products1_idx` (`Products_id` ASC, `Products_admin_id` ASC, `Products_Category_id` ASC) ,
  INDEX `fk_Order_has_Products_Order1_idx` (`Order_id` ASC) ,
  CONSTRAINT `fk_Order_has_Products_Order1`
    FOREIGN KEY (`Order_id`)
    REFERENCES `craft_api`.`Order` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Order_has_Products_Products1`
    FOREIGN KEY (`Products_id` , `Products_admin_id` , `Products_Category_id`)
    REFERENCES `craft_api`.`Products` (`id` , `admin_id` , `Category_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
