#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

set -e

branch="$(git rev-parse --abbrev-ref HEAD)"
allBranch="$(git branch -a)"
_user="$(id -u -n)"
if [[ "$branch" = "master" && "$_user" != "b3ns44d" ]]; then
    echo "$_user You can't commit directly to master branch but you can switch to one of those branches-> $allBranch"
    exit 0
fi
echo '🏗️👷 Styling, testing and building your project before committing'
yarn format
# Check Prettier standards
yarn check-format ||
    (
        echo '🤢🤮🤢🤮 Its F**KING RAW - Your styling looks disgusting. 🤢🤮🤢🤮
            Prettier Check Failed. Run yarn format, add changes and try commit again.'
        false
    )

# Check ESLint Standards
yarn check-lint ||
    (
        echo '😤🏀👋😤 Get that weak s**t out of here! 😤🏀👋😤 
                ESLint Check Failed. Make the required changes listed above, add changes and try to commit again.'
        false
    )

# If everything passes... Now we can commit
echo '🤔🤔🤔🤔... Alright... Code looks good to me... Trying to jest now. 🤔🤔🤔🤔'

yarn test ||
    (
        echo '❌👷🔨❌ Better call Bob... Because your test failed ❌👷🔨❌
            Next test failed: View the errors above to see why. 
    '
        false
    )

# If everything passes... Now we can commit
echo '✅✅✅✅ You win this time... I am committing this now. ✅✅✅✅'
