#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

set -e

branch="$(git rev-parse --abbrev-ref HEAD)"
allBranch="$(git branch -a)"

_user="$(id -u -n)"

# here i just check if branch is master and i make b3ns44d the root
if [[ "$branch" = "master" && "$_user" != "b3ns44d" ]]; then
    echo "$_user You can't push directly to master branch but we will pull the master branch to you 🌝"
    git pull origin master
    echo "Try to push somewhere else you piece of shit 🙂"
    echo "this is list of all branches->  $allBranch"
    exit 0
fi

# echo '🏗️ Pulling shit out wait a moment please'
# git pull origin master ||
#     (
#         echo '🤢🤮🤢🤮 SHIIIT BRO - Your brnach need some fixing. try to fix it and try again'
#         false
#     )
# If everything passes... Now we can push
echo '✅✅✅✅ everything looks good pushing your shit now. ✅✅✅✅'
